periodic_table = [
    {
        "atomic number": 1,
        "element": "hydrogen",
        "atomic weight": 1.008,
        "class": "nonmetal",
        "phase": "gas",
        "period": 1,
        "electron config": '1s1',
        "melting point": -434.5,
        "boiling point": -423.2,
        "symbol": "H",
    }, {
        "atomic number": 2,
        "element": "helium",
        "atomic weight": 4.003,
        "class": "noble gas",
        "phase": "gas",
        "period": 1,
        "electron config": '1s2',
        "melting point": -458.0,
        "boiling point": -452.1,
        "symbol": "He"
    },
    {
        "atomic number": 3,
        "element": "lithium",
        "atomic weight": 6.941,
        "class": "alkali metal",
        "phase": "solid",
        "period": 2,
        "electron config": '1s2 2s1',
        "melting point": 357.0,
        "boiling point": 2426.0,
        "symbol": "Li"
    },
    {
        "atomic number": 4,
        "element": "beryllium",
        "atomic weight": 9.012,
        "class": "alkaline earth metal",
        "phase": "solid",
        "period": 2,
        "electron config": '1s2 2s2',
        "melting point": 2349.0,
        "boiling point": 5378.0,
        "symbol": "Be"
    },
    {
        "atomic number": 5,
        "element": "boron",
        "atomic weight": 10.811,
        "class": "metalloid",
        "phase": "solid",
        "period": 2,
        "electron config": '1s2 2s2 2p1',
        "melting point": 3769.0,
        "boiling point": 7101.0,
        "symbol": "B"
    },
    {
        "atomic number": 6,
        "element": "carbon",
        "atomic weight": 12.011,
        "class": "nonmetal",
        "phase": "solid",
        "period": 2,
        "electron config": '1s2 2s2 2p2',
        "melting point": 6420.0,
        "boiling point": 8721.0,
        "symbol": "C"
    },
    {
        "atomic number": 7,
        "element": "nitrogen",
        "atomic weight": 14.007,
        "class": "nonmetal",
        "phase": "gas",
        "period": 2,
        "electron config": '1s2 2s2 2p3',
        "melting point": -346.0,
        "boiling point": -320.4,
        "symbol": "N"
    },
    {
        "atomic number": 8,
        "element": "oxygen",
        "atomic weight": 15.999,
        "class": "nonmetal",
        "phase": "gas",
        "period": 2,
        "electron config": '1s2 2s2 2p4',
        "melting point": -361.8,
        "boiling point": -297.3,
        "symbol": "O"
    },
    {
        "atomic number": 9,
        "element": "fluorine",
        "atomic weight": 18.998,
        "class": "halogen",
        "phase": "gas",
        "period": 2,
        "electron config": '1s2 2s2 2p5',
        "melting point": -363.3,
        "boiling point": -306.6,
        "symbol": "F"
    },
    {
        "atomic number": 10,
        "element": "neon",
        "atomic weight": 20.180,
        "class": "noble gas",
        "phase": "gas",
        "period": 2,
        "electron config": '1s2 2s2 2p6',
        "melting point": -415.5,
        "boiling point": -410.9,
        "symbol": "Ne"
    },
    {
        "atomic number": 11,
        "element": "sodium",
        "atomic weight": 22.990,
        "class": "alkali metal",
        "phase": "solid",
        "period": 3,
        "electron config": '1s2 2s2 2p6 3s1',
        "melting point": 208.0,
        "boiling point": 1621.0,
        "symbol": "Na"
    },
    {
        "atomic number": 12,
        "element": "magnesium",
        "atomic weight": 24.305,
        "class": "alkaline earth metal",
        "phase": "solid",
        "period": 3,
        "electron config": '1s2 2s2 2p6 3s2',
        "melting point": 1202.0,
        "boiling point": 1996.0,
        "symbol": "Mg"
    },
    {
        "atomic number": 13,
        "element": "aluminum",
        "atomic weight": 26.982,
        "class": "poor metal",
        "phase": "solid",
        "period": 3,
        "electron config": '1s2 2s2 2p6 3s2 3p1',
        "melting point": 1221.0,
        "boiling point": 4478.0,
        "symbol": "Al"
    },
    {
        "atomic number": 14,
        "element": "silicon",
        "atomic weight": 28.086,
        "class": "metalloid",
        "phase": "solid",
        "period": 3,
        "electron config": '1s2 2s2 2p6 3s2 3p2',
        "melting point": 2577.0,
        "boiling point": 5909.0,
        "symbol": "Si"
    },
    {
        "atomic number": 15,
        "element": "phosphorus",
        "atomic weight": 30.974,
        "class": "nonmetal",
        "phase": "solid",
        "period": 3,
        "electron config": '1s2 2s2 2p6 3s2 3p3',
        "melting point": 111.6,
        "boiling point": 536.9,
        "symbol": "P"
    },
    {
        "atomic number": 16,
        "element": "sulfur",
        "atomic weight": 32.066,
        "class": "nonmetal",
        "phase": "solid",
        "period": 3,
        "electron config": '1s2 2s2 2p6 3s2 3p4',
        "melting point": 239.4,
        "boiling point": 832.3,
        "symbol": "S"
    },
    {
        "atomic number": 17,
        "element": "chlorine",
        "atomic weight": 35.453,
        "class": "halogen",
        "phase": "gas",
        "period": 3,
        "electron config": '1s2 2s2 2p6 3s2 3p5',
        "melting point": -150.7,
        "boiling point": -29.3,
        "symbol": "Cl"
    },
    {
        "atomic number": 18,
        "element": "argon",
        "atomic weight": 39.948,
        "class": "noble gas",
        "phase": "gas",
        "period": 3,
        "electron config": '1s2 2s2 2p6 3s2 3p6',
        "melting point": -308.8,
        "boiling point": -302.5,
        "symbol": "Ar"
    },
    {
        "atomic number": 19,
        "element": "potassium",
        "atomic weight": 39.098,
        "class": "alkali metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 4s1',
        "melting point": 146.3,
        "boiling point": 1398.0,
        "symbol": "K"
    },
    {
        "atomic number": 20,
        "element": "calcium",
        "atomic weight": 40.078,
        "class": "alkaline earth metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 4s2',
        "melting point": 1548.0,
        "boiling point": 2703.0,
        "symbol": "Ca"
    },
    {
        "atomic number": 21,
        "element": "scandium",
        "atomic weight": 44.956,
        "class": "transition metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d1 4s2',
        "melting point": 2806.0,
        "boiling point": 5137.0,
        "symbol": "Sc"
    },
    {
        "atomic number": 22,
        "element": "titanium",
        "atomic weight": 47.867,
        "class": "transition metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d2 4s2',
        "melting point": 3034.0,
        "boiling point": 5948.0,
        "symbol": "Ti"
    },
    {
        "atomic number": 23,
        "element": "vanadium",
        "atomic weight": 50.942,
        "class": "transition metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d3 4s2',
        "melting point": 3470.0,
        "boiling point": 6165.0,
        "symbol": "V"
    },
    {
        "atomic number": 24,
        "element": "chromium",
        "atomic weight": 51.996,
        "class": "transition metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d5 4s1',
        "melting point": 3465.0,
        "boiling point": 4841.0,
        "symbol": "Cr"
    },
    {
        "atomic number": 25,
        "element": "manganese",
        "atomic weight": 54.938,
        "class": "transition metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d5 4s2',
        "melting point": 2275.0,
        "boiling point": 3742.0,
        "symbol": "Mn"
    },
    {
        "atomic number": 26,
        "element": "iron",
        "atomic weight": 55.933,
        "class": "transition metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d6 4s2',
        "melting point": 2800.0,
        "boiling point": 5184.0,
        "symbol": "Fe"
    },
    {
        "atomic number": 27,
        "element": "cobalt",
        "atomic weight": 58.933,
        "class": "transition metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d7 4s2',
        "melting point": 2723.0,
        "boiling point": 5198.0,
        "symbol": "Co"
    },
    {
        "atomic number": 28,
        "element": "nickel",
        "atomic weight": 58.693,
        "class": "transition metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d8 4s2',
        "melting point": 2651.0,
        "boiling point": 5275.0,
        "symbol": "Ni"
    },
    {
        "atomic number": 29,
        "element": "copper",
        "atomic weight": 63.546,
        "class": "transition metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s1',
        "melting point": 1984.0,
        "boiling point": 5300.0,
        "symbol": "Cu"
    },
    {
        "atomic number": 30,
        "element": "zinc",
        "atomic weight": 65.39,
        "class": "transition metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2',
        "melting point": 787.2,
        "boiling point": 1664.0,
        "symbol": "Zn"
    },
    {
        "atomic number": 31,
        "element": "gallium",
        "atomic weight": 69.732,
        "class": "poor metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p1',
        "melting point": 85.6,
        "boiling point": 3999.0,
        "symbol": "Ga"
    },
    {
        "atomic number": 32,
        "element": "germanium",
        "atomic weight": 72.61,
        "class": "metalloid",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p2',
        "melting point": 1721.0,
        "boiling point": 5131.0,
        "symbol": "Ge"
    },
    {
        "atomic number": 33,
        "element": "arsenic",
        "atomic weight": 74.992,
        "class": "metalloid",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p3',
        "melting point": 1720.9,
        "boiling point": 5108.0,
        "symbol": "As"
    },
    {
        "atomic number": 34,
        "element": "selenium",
        "atomic weight": 78.09,
        "class": "non metal",
        "phase": "solid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p4',
        "melting point": 430.0,
        "boiling point": 1265.0,
        "symbol": "Se"
    },
    {
        "atomic number": 35,
        "element": "bromine",
        "atomic weight": 79.904,
        "class": "halogen",
        "phase": "liquid",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p5',
        "melting point": 18.8,
        "boiling point": 138.0,
        "symbol": "Br"
    },
    {
        "atomic number": 36,
        "element": "krypton",
        "atomic weight": 84.80,
        "class": "noble gas",
        "phase": "gas",
        "period": 4,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6',
        "melting point": -251.3,
        "boiling point": -243.8,
        "symbol": "Kr"
    },
    {
        "atomic number": 37,
        "element": "rubidium",
        "atomic weight": 85.468,
        "class": "alkali metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 5s1',
        "melting point": 102.8,
        "boiling point": 1270.0,
        "symbol": "Rb"
    },
    {
        "atomic number": 38,
        "element": "strontium",
        "atomic weight": 87.62,
        "class": "alkaline earth metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 5s2',
        "melting point": 1431.0,
        "boiling point": 2519.0,
        "symbol": "Sr"
    },
    {
        "atomic number": 39,
        "element": "yttrium",
        "atomic weight": 88.906,
        "class": "transition metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d1 5s2',
        "melting point": 2779.0,
        "boiling point": 6040.0,
        "symbol": "Y"
    },
    {
        "atomic number": 40,
        "element": "zirconium",
        "atomic weight": 91.224,
        "class": "transition metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d2 5s2',
        "melting point": 3371.0,
        "boiling point": 7968.0,
        "symbol": "Zr"
    },
    {
        "atomic number": 41,
        "element": "niobium",
        "atomic weight": 92.906,
        "class": "transition metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d4 5s1',
        "melting point": 4491.0,
        "boiling point": 8901.0,
        "symbol": "Nb"
    },
    {
        "atomic number": 42,
        "element": "molybdenum",
        "atomic weight": 95.94,
        "class": "transition metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d5 5s1',
        "melting point": 4753.0,
        "boiling point": 8382.0,
        "symbol": "Mo"
    },
    {
        "atomic number": 43,
        "element": "technetium",
        "atomic weight": 98.907,
        "class": "transition metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d5 5s2',
        "melting point": 3915.0,
        "boiling point": 7709.0,
        "symbol": "Tc"
    },
    {
        "atomic number": 44,
        "element": "ruthenium",
        "atomic weight": 101.07,
        "class": "transition metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d7 5s1',
        "melting point": 4233.0,
        "boiling point": 7502.0,
        "symbol": "Ru"
    },
    {
        "atomic number": 45,
        "element": "rhodium",
        "atomic weight": 102.906,
        "class": "transition metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d8 5s1',
        "melting point": 3567.0,
        "boiling point": 6686.0,
        "symbol": "Rh"
    },
    {
        "atomic number": 46,
        "element": "palladium",
        "atomic weight": 106.42,
        "class": "transition metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s0',
        "melting point": 2831.0,
        "boiling point": 5365.0,
        "symbol": "Pd"
    },
    {
        "atomic number": 47,
        "element": "silver",
        "atomic weight": 107.868,
        "class": "transition metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s1',
        "melting point": 1763.0,
        "boiling point": 3924.0,
        "symbol": "Ag"
    },
    {
        "atomic number": 48,
        "element": "cadmium",
        "atomic weight": 112.411,
        "class": "transition metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2',
        "melting point": 609.9,
        "boiling point": 3924.0,
        "symbol": "Cd"
    },
    {
        "atomic number": 49,
        "element": "indium",
        "atomic weight": 114.818,
        "class": "transition metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p1',
        "melting point": 313.9,
        "boiling point": 3762.0,
        "symbol": "In"
    },
    {
        "atomic number": 50,
        "element": "tin",
        "atomic weight": 118.71,
        "class": "transition metal",
        "phase": "solid",
        "period": 5,
        "electron config": '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p2',
        "melting point": 449.5,
        "boiling point": 4716.0,
        "symbol": "Sn"
    },
]